require "test_helper"

class BookingsFlowTest < ActionDispatch::IntegrationTest
  include ActiveSupport::Testing::TimeHelpers

  setup do
    @client = Client.create!(
      name: "Le Salon Des gâté",
      slug: "salon-des-gate"
    )

    @service = @client.services.create!(
      name: "Coupe homme",
      duration_minutes: 30,
      price_cents: 2500
    )
  end

  test "new creates a pending booking for a valid slot" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      get new_service_booking_path(
        @client.slug,
        @service,
        start_time: Time.zone.local(2026, 3, 16, 10, 0, 0)
      )

      assert_response :success

      booking = Booking.last
      assert_not_nil booking
      assert_equal @client.id, booking.client_id
      assert_equal @service.id, booking.service_id
      assert_equal "pending", booking.booking_status
      assert_equal Time.zone.local(2026, 3, 16, 10, 0, 0), booking.booking_start_time
      assert_equal Time.zone.local(2026, 3, 16, 10, 30, 0), booking.booking_end_time
      assert_not_nil booking.booking_expires_at
    end
  end

  test "new redirects when slot is invalid" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      get new_service_booking_path(
        @client.slug,
        @service,
        start_time: "bonjour"
      )

      assert_redirected_to public_client_path(@client.slug, service_id: @service.id)
      follow_redirect!
      assert_match "créneau sélectionné est invalide", response.body.downcase
    end
  end

  test "new redirects when slot is not generated by the system" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      # 08:00 n'est pas un créneau valide du generator (ouverture à 09:00)
      get new_service_booking_path(
        @client.slug,
        @service,
        start_time: Time.zone.local(2026, 3, 16, 8, 0, 0)
      )

      assert_redirected_to public_client_path(@client.slug, service_id: @service.id, date: Date.new(2026, 3, 16))
    end
  end

  test "create confirms a valid pending booking" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      booking = @client.bookings.create!(
        service: @service,
        booking_start_time: Time.zone.local(2026, 3, 16, 11, 0, 0),
        booking_end_time: Time.zone.local(2026, 3, 16, 11, 30, 0),
        booking_status: :pending,
        booking_expires_at: 5.minutes.from_now
      )

      post confirm_booking_path(@client.slug, booking), params: {
        booking: {
          customer_first_name: "Léonard",
          customer_last_name: "Boisson",
          customer_email: "leo@example.com"
        }
      }

      assert_redirected_to booking_success_path(@client.slug, booking)

      booking.reload
      assert_equal "confirmed", booking.booking_status
      assert_equal "Léonard", booking.customer_first_name
      assert_equal "Boisson", booking.customer_last_name
      assert_equal "leo@example.com", booking.customer_email
    end
  end

  test "create redirects when pending booking is expired" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      booking = @client.bookings.create!(
        service: @service,
        booking_start_time: Time.zone.local(2026, 3, 16, 12, 0, 0),
        booking_end_time: Time.zone.local(2026, 3, 16, 12, 30, 0),
        booking_status: :pending,
        booking_expires_at: 1.minute.ago
      )

      post confirm_booking_path(@client.slug, booking), params: {
        booking: {
          customer_first_name: "Léonard",
          customer_last_name: "Boisson",
          customer_email: "leo@example.com"
        }
      }

      assert_redirected_to public_client_path(
        @client.slug,
        service_id: @service.id,
        date: Date.new(2026, 3, 16)
      )

      booking.reload
      assert_equal "pending", booking.booking_status
      assert_nil booking.customer_first_name
    end
  end

  test "create redirects when booking is no longer pending" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      booking = @client.bookings.create!(
        service: @service,
        booking_start_time: Time.zone.local(2026, 3, 16, 13, 0, 0),
        booking_end_time: Time.zone.local(2026, 3, 16, 13, 30, 0),
        booking_status: :confirmed,
        customer_first_name: "Léonard",
        customer_last_name: "Boisson",
        customer_email: "leo@example.com"
      )

      post confirm_booking_path(@client.slug, booking), params: {
        booking: {
          customer_first_name: "Test",
          customer_last_name: "User",
          customer_email: "test@example.com"
        }
      }

      assert_redirected_to public_client_path(
        @client.slug,
        service_id: @service.id,
        date: Date.new(2026, 3, 16)
      )

      booking.reload
      assert_equal "confirmed", booking.booking_status
      assert_equal "Léonard", booking.customer_first_name
    end
  end
end
