require "test_helper"

class Bookings::CreatePendingTest < ActiveSupport::TestCase
  include ActiveSupport::Testing::TimeHelpers

  setup do
    @client = Client.create!(
      name: "Le Salon Des gâté",
      slug: "salon-des-gate"
    )
    create_weekday_opening_hours_for(@client)

    @enseigne = @client.enseignes.create!(
      name: "Enseigne principale"
    )

    @service = @client.services.create!(
      name: "Coupe homme",
      duration_minutes: 30,
      price_cents: 2500
    )
  end

  test "creates a pending booking for a valid slot" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      slot = Time.zone.local(2026, 3, 16, 10, 0, 0)

      result = Bookings::CreatePending.new(
        client: @client,
        enseigne: @enseigne,
        service: @service,
        booking_start_time: slot
      ).call

      assert result.success?, "CreatePending should succeed for valid slot; got error_code=#{result.error_code.inspect}"
      assert_not_nil result.booking
      assert_nil result.error_message

      booking = result.booking
      assert_equal "pending", booking.booking_status, "Booking should be pending after CreatePending success"
      assert_equal @enseigne.id, booking.enseigne_id
      assert_equal slot, booking.booking_start_time
      assert_equal slot + 30.minutes, booking.booking_end_time
      assert_not_nil booking.booking_expires_at
    end
  end

  test "creates a pending booking with the explicit enseigne provided by the public flow" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      slot = Time.zone.local(2026, 3, 16, 10, 30, 0)

      result = Bookings::CreatePending.new(
        client: @client,
        enseigne: @enseigne,
        service: @service,
        booking_start_time: slot
      ).call

      assert result.success?
      assert_equal @enseigne.id, result.booking.enseigne_id
    end
  end

  test "fails when booking_start_time is nil" do
    result = Bookings::CreatePending.new(
      client: @client,
      enseigne: @enseigne,
      service: @service,
      booking_start_time: nil
    ).call

    assert_not result.success?, "CreatePending should fail when slot is nil"
    assert_nil result.booking
    assert_equal Bookings::Errors::INVALID_SLOT, result.error_code
    assert_equal "Le créneau sélectionné est invalide.", result.error_message
  end

  test "fails when slot is not generated by the system" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      invalid_slot = Time.zone.local(2026, 3, 16, 8, 0, 0)

      result = Bookings::CreatePending.new(
        client: @client,
        enseigne: @enseigne,
        service: @service,
        booking_start_time: invalid_slot
      ).call

      assert_not result.success?
      assert_nil result.booking
      assert_equal Bookings::Errors::SLOT_NOT_BOOKABLE, result.error_code
      assert_equal "Le créneau sélectionné n'est pas réservable.", result.error_message
    end
  end

  test "fails when slot is already blocked by confirmed booking" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      slot = Time.zone.local(2026, 3, 16, 11, 0, 0)

      @client.bookings.create!(
        enseigne: @enseigne,
        service: @service,
        booking_start_time: slot,
        booking_end_time: slot + 30.minutes,
        booking_status: :confirmed,
        customer_first_name: "Leonard",
        customer_last_name: "Boisson",
        customer_email: "leo@example.com"
      )

      result = Bookings::CreatePending.new(
        client: @client,
        enseigne: @enseigne,
        service: @service,
        booking_start_time: slot
      ).call

      assert_not result.success?
      assert_nil result.booking
      assert_equal Bookings::Errors::SLOT_UNAVAILABLE, result.error_code
      assert_equal "Le créneau sélectionné n'est plus disponible.", result.error_message
    end
  end

  test "fails when new pending overlaps confirmed booking with different start_time" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      confirmed_start = Time.zone.local(2026, 3, 16, 10, 0, 0)
      confirmed_end   = confirmed_start + 30.minutes

      @client.bookings.create!(
        enseigne: @enseigne,
        service: @service,
        booking_start_time: confirmed_start,
        booking_end_time: confirmed_end,
        booking_status: :confirmed,
        customer_first_name: "Leonard",
        customer_last_name: "Boisson",
        customer_email: "leo@example.com"
      )

      overlapping_start = Time.zone.local(2026, 3, 16, 10, 15, 0)

      result = Bookings::CreatePending.new(
        client: @client,
        enseigne: @enseigne,
        service: @service,
        booking_start_time: overlapping_start
      ).call

      assert_not result.success?
      assert_nil result.booking
      assert_equal Bookings::Errors::SLOT_UNAVAILABLE, result.error_code
      assert_equal "Le créneau sélectionné n'est plus disponible.", result.error_message
    end
  end

  test "allows pending when new slot starts at confirmed booking end" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      confirmed_start = Time.zone.local(2026, 3, 16, 10, 0, 0)
      confirmed_end   = confirmed_start + 30.minutes

      @client.bookings.create!(
        enseigne: @enseigne,
        service: @service,
        booking_start_time: confirmed_start,
        booking_end_time: confirmed_end,
        booking_status: :confirmed,
        customer_first_name: "Leonard",
        customer_last_name: "Boisson",
        customer_email: "leo@example.com"
      )

      border_start = confirmed_end

      result = Bookings::CreatePending.new(
        client: @client,
        enseigne: @enseigne,
        service: @service,
        booking_start_time: border_start
      ).call

      assert result.success?
      assert_equal "pending", result.booking.booking_status
      assert_equal border_start, result.booking.booking_start_time
    end
  end

  test "fails when slot is already blocked by active pending booking" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      slot = Time.zone.local(2026, 3, 16, 12, 0, 0)

      @client.bookings.create!(
        enseigne: @enseigne,
        service: @service,
        booking_start_time: slot,
        booking_end_time: slot + 30.minutes,
        booking_status: :pending,
        booking_expires_at: BookingRules.pending_expires_at
      )

      result = Bookings::CreatePending.new(
        client: @client,
        enseigne: @enseigne,
        service: @service,
        booking_start_time: slot
      ).call

      assert_not result.success?
      assert_nil result.booking
      assert_equal Bookings::Errors::SLOT_UNAVAILABLE, result.error_code
      assert_equal "Le créneau sélectionné n'est plus disponible.", result.error_message
    end
  end

  test "allows slot when previous pending booking is expired" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      slot = Time.zone.local(2026, 3, 16, 13, 0, 0)

      @client.bookings.create!(
        enseigne: @enseigne,
        service: @service,
        booking_start_time: slot,
        booking_end_time: slot + 30.minutes,
        booking_status: :pending,
        booking_expires_at: 1.minute.ago
      )

      result = Bookings::CreatePending.new(
        client: @client,
        enseigne: @enseigne,
        service: @service,
        booking_start_time: slot
      ).call

      assert result.success?
      assert_equal "pending", result.booking.booking_status
      assert_equal slot, result.booking.booking_start_time
    end
  end

  test "fails without explicit enseigne" do
    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      slot = Time.zone.local(2026, 3, 16, 16, 0, 0)

      result = Bookings::CreatePending.new(
        client: @client,
        enseigne: nil,
        service: @service,
        booking_start_time: slot
      ).call

      assert_not result.success?
      assert_equal Bookings::Errors::PENDING_CREATION_FAILED, result.error_code
    end
  end

  test "fails with inactive enseigne" do
    inactive_enseigne = @client.enseignes.create!(name: "Inactive", active: false)

    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      slot = Time.zone.local(2026, 3, 16, 16, 30, 0)

      result = Bookings::CreatePending.new(
        client: @client,
        enseigne: inactive_enseigne,
        service: @service,
        booking_start_time: slot
      ).call

      assert_not result.success?
      assert_equal Bookings::Errors::PENDING_CREATION_FAILED, result.error_code
    end
  end

  test "fails when service belongs to another client" do
    other_client = Client.create!(
      name: "Autre salon",
      slug: "autre-salon"
    )
    other_service = other_client.services.create!(
      name: "Massage",
      duration_minutes: 45,
      price_cents: 5000
    )

    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      slot = Time.zone.local(2026, 3, 16, 10, 0, 0)

      booking_singleton = class << Booking; self; end
      booking_singleton.alias_method :create_without_service_context_guard_test!, :create!
      booking_singleton.define_method(:create!) do |_attrs|
        raise "Booking.create! should not be called for invalid service context"
      end

      begin
        result = Bookings::CreatePending.new(
          client: @client,
          enseigne: @enseigne,
          service: other_service,
          booking_start_time: slot
        ).call

        assert_not result.success?
        assert_nil result.booking
        assert_equal Bookings::Errors::PENDING_CREATION_FAILED, result.error_code
      ensure
        booking_singleton.alias_method :create!, :create_without_service_context_guard_test!
        booking_singleton.remove_method :create_without_service_context_guard_test!
      end
    end
  end

  test "uses enseigne opening hours when the client has a single enseigne" do
    create_weekday_opening_hours_for_enseigne(@enseigne, opens_at: "10:00", closes_at: "16:00")

    travel_to Time.zone.local(2026, 3, 15, 8, 0, 0) do
      result = Bookings::CreatePending.new(
        client: @client,
        enseigne: @enseigne,
        service: @service,
        booking_start_time: Time.zone.local(2026, 3, 16, 9, 0, 0)
      ).call

      assert_not result.success?
      assert_equal Bookings::Errors::SLOT_NOT_BOOKABLE, result.error_code
    end
  end
end
